name: Classification Continuous Deployment (CD)

on:
  push:
    branches:
      - master

env:
  GCE_AUTH: ${{ secrets.GCE_AUTH }}
  GCE_PROJECT: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}

jobs:
  train-model:
    name: Train model in GCE
    runs-on: ubuntu-latest
    steps:
      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '285.0.0'

      - name: Google Cloud Authentication
        run: |
          echo "$GCE_AUTH" | base64 --decode > "$HOME"/gcloud.json
          sh -c "gcloud auth activate-service-account --key-file=$HOME/gcloud.json $*"
          gcloud config set project ${{ secrets.GCE_PROJECT }}
          rm "$HOME"/gcloud.json

      - name: Configure SSH to instance
        run: |
          gcloud compute config-ssh

      - name: Testing SSH connection
        run: |
          gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" --command "ls -la"
