name: Client CI

on:
  push:
    branches: [master]
    paths: ["client/**"]
  pull_request:
    branches: [master]
    paths: ["client/**"]

jobs:
  lint:
    name: Check project linting
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Install dependencies
        working-directory: client/
        run: npm install

      - name: Check linting
        working-directory: client/
        run: npm run lint

  ng-build:
    name: Angular build
    needs: [lint]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Install dependencies
        working-directory: client/
        run: npm install

      - name: Build project
        working-directory: client/
        run: npm run build -- --prod

  ng-test:
    name: Run Angular tests
    needs: [lint, ng-build]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Install dependencies
        working-directory: client/
        run: npm install

      - name: Run tests
        working-directory: client/
        run: npm test

      - name: Run E2E tests
        working-directory: client/
        run: npm run e2e
