name: Embedded CD

on:
  push:
    branches: [master, feature/embedded]
    paths: ["embedded/raspberry/**"]

env:
  EMBEDDED_DEPLOYMENT_PATH: ${{ secrets.EMBEDDED_DEPLOYMENT_PATH }}

jobs:
  deploy:
    name: Deploy on Raspberry
    runs-on: self-hosted

    steps:
      - name: Update embedded server code from repository
        run: |
          svn export https://github.com/braind3d/traffic-brain/trunk/embedded/raspberry $EMBEDDED_DEPLOYMENT_PATH --force

      - name: Installing missing dependencies
        run: |
          pip3 install -r ~/traffic-brain/requirements.txt

      - name: Scheduling reboot
        run: |
          shutdown -r 1
