name: Embedded CI

on:
  push:
    branches: [master]
    paths: ["embedded/raspberry/**"]
  pull_request:
    branches: [master]
    paths: ["embedded/raspberry/**"]

jobs:
  lint:
    name: Check project linting
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        working-directory: embedded/raspberry/
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        working-directory: embedded/raspberry/
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    name: Run all tests
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        working-directory: embedded/raspberry/
        run: |
          python3 -m pip install --upgrade pip3
          pip3 install pytest
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

      - name: Test with pytest
        working-directory: embedded/raspberry/
        run: |
          pytest
