name: Server CI
on:
  push:
    branches: [master]
    paths: ["server/**"]
  pull_request:
    branches: [master]
    paths: ["server/**"]

jobs:
  build-test:
    name: Build and Test with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
